services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app-blog
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/blog-pos-fiap
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-blog
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app

  mongodb:
    image: mongo:7.0.0
    container_name: mongodb-blog
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: